// @ts-nocheck
import {
  connectDb,
  disconnectDb,
  countSummary,
  plusDays,
  replaceAuditLogs,
  replaceNotifications,
  upsertAppointment,
  upsertDiagnosis,
  upsertPatient,
  upsertPrescription,
  upsertResource,
  upsertService,
  upsertStaff,
  upsertUnavailableBlock,
  upsertUser,
  upsertVisit,
  upsertVital,
  withTime,
} from "./seedSupport";

async function seedDemo() {
  await connectDb();
  console.log("Connected to MongoDB");

  const now = new Date();

  const users = {
    superadmin: await upsertUser({
      phone: "99335671",
      password: "Test!123",
      firstname: "Хишигбаяр",
      lastname: "Бал",
      role: "superadmin",
      email: "khishigbayar.bal@demo.num.edu.mn",
      gender: "male",
    }),
    doctorGeneral: await upsertUser({
      phone: "99110011",
      password: "Doctor!123",
      firstname: "Эрдэнэбат",
      lastname: "Мөнхтөр",
      role: "doctor",
      email: "erdenebat.munkhtur@demo.num.edu.mn",
      gender: "male",
    }),
    nurse: await upsertUser({
      phone: "99110012",
      password: "Nurse!123",
      firstname: "Оюунчимэг",
      lastname: "Сүхээ",
      role: "nurse",
      email: "oyuunchimeg.sukhee@demo.num.edu.mn",
      gender: "female",
    }),
    operator: await upsertUser({
      phone: "99110013",
      password: "Operator!123",
      firstname: "Саруул",
      lastname: "Түмэнжаргал",
      role: "data_operator",
      email: "saruul.tumenjargal@demo.num.edu.mn",
      gender: "female",
    }),
    patient1: await upsertUser({
      phone: "88112233",
      password: "Patient!123",
      firstname: "Тэмүүлэн",
      lastname: "Бат-Оргил",
      role: "patient",
      email: "temuulen.batorgil@demo.num.edu.mn",
      gender: "male",
      birthdate: new Date("2003-04-17"),
    }),
    patient2: await upsertUser({
      phone: "88112244",
      password: "Patient!123",
      firstname: "Номин-Эрдэнэ",
      lastname: "Батчимэг",
      role: "patient",
      email: "nominerdene.batchimeg@demo.num.edu.mn",
      gender: "female",
      birthdate: new Date("1999-11-02"),
    }),
    patient3: await upsertUser({
      phone: "88112255",
      password: "Patient!123",
      firstname: "Анужин",
      lastname: "Саран",
      role: "patient",
      email: "anujin.saran@demo.num.edu.mn",
      gender: "female",
      birthdate: new Date("2001-08-24"),
    }),
    patient4: await upsertUser({
      phone: "88112266",
      password: "Patient!123",
      firstname: "Мөнхжин",
      lastname: "Энхсайхан",
      role: "patient",
      email: "munkhjin.enkhsaikhan@demo.num.edu.mn",
      gender: "male",
      birthdate: new Date("1988-01-15"),
    }),
    patient5: await upsertUser({
      phone: "88112277",
      password: "Patient!123",
      firstname: "Энхжин",
      lastname: "Батсүх",
      role: "patient",
      email: "enkhjin.batsukh@demo.num.edu.mn",
      gender: "female",
      birthdate: new Date("2004-06-11"),
    }),
    patient6: await upsertUser({
      phone: "88112288",
      password: "Patient!123",
      firstname: "Ган-Эрдэнэ",
      lastname: "Чулуун",
      role: "patient",
      email: "ganerdene.chuluun@demo.num.edu.mn",
      gender: "male",
      birthdate: new Date("1997-12-19"),
    }),
  };

  const staff = {
    doctorGeneral: await upsertStaff({
      userId: users.doctorGeneral._id,
      staffType: "doctor",
      specialization: "Ерөнхий эмч",
      licenseNumber: "DOC-DEMO-001",
      title: "Ахлах эмч",
      bio: "Оюутан, ажилтны анхан үзлэг болон үзлэгийн түүхийн workflow-г хариуцна.",
      maxDailyAppointments: 18,
    }),
    nurse: await upsertStaff({
      userId: users.nurse._id,
      staffType: "nurse",
      title: "Сувилагч",
      bio: "Дусал, урьдчилсан хэмжилт, сувилгааны урсгал хариуцна.",
      maxDailyAppointments: 28,
    }),
    operator: await upsertStaff({
      userId: users.operator._id,
      staffType: "data_operator",
      title: "Бүртгэлийн ажилтан",
      bio: "Өвчтөн бүртгэл, цаг товлолт хариуцна.",
      maxDailyAppointments: 40,
    }),
  };

  const services = {
    consult: await upsertService({
      code: "CONSULT_GENERAL",
      name: "Ерөнхий эмчийн үзлэг",
      category: "consultation",
      description: "Анхан үзлэг, дараах хяналт",
      defaultDurationMinutes: 20,
      defaultBufferMinutes: 5,
      requiresDoctor: true,
    }),
    injection: await upsertService({
      code: "NURSE_INJECTION",
      name: "Сувилагчийн тариа",
      category: "injection",
      description: "Төлөвлөгөөт тариа, богино ажилбар",
      defaultDurationMinutes: 15,
      requiresNurse: true,
    }),
    infusion: await upsertService({
      code: "IV_INFUSION",
      name: "Дусал",
      category: "infusion",
      description: "Дуслын өрөөнд хийх үйлчилгээ",
      defaultDurationMinutes: 90,
      requiresNurse: true,
    }),
    massage: await upsertService({
      code: "MASSAGE_CHAIR",
      name: "Массажны сандал",
      category: "device",
      description: "Сэргээн засах төхөөрөмж",
      defaultDurationMinutes: 30,
      defaultBufferMinutes: 10,
      requiresDevice: true,
    }),
    irradiation: await upsertService({
      code: "IRRADIATION",
      name: "Шарлагын аппарат",
      category: "device",
      description: "Шарлагын төхөөрөмжийн үйлчилгээ",
      defaultDurationMinutes: 20,
      defaultBufferMinutes: 10,
      requiresDevice: true,
    }),
  };

  const resources = {
    doctorGeneral: await upsertResource({
      name: "Ерөнхий эмчийн кабинет 101",
      type: "doctor",
      category: "consultation",
      staffId: staff.doctorGeneral._id,
      serviceIds: [services.consult._id],
      room: "101",
      capacity: 1,
      slotIntervalMinutes: 25,
      defaultDurationMinutes: 20,
      defaultBufferMinutes: 5,
    }),
    injectionRoom: await upsertResource({
      name: "Тарилгын өрөө 201",
      type: "room",
      category: "injection",
      serviceIds: [services.injection._id],
      room: "201",
      capacity: 1,
      slotIntervalMinutes: 15,
      defaultDurationMinutes: 15,
      defaultBufferMinutes: 0,
    }),
    infusionRoom: await upsertResource({
      name: "Дуслын өрөө",
      type: "capacity_room",
      category: "infusion",
      serviceIds: [services.infusion._id],
      room: "301",
      capacity: 8,
      slotIntervalMinutes: 30,
      defaultDurationMinutes: 90,
      defaultBufferMinutes: 0,
    }),
    massageChair: await upsertResource({
      name: "Массажны сандал 1",
      type: "device",
      category: "massage",
      serviceIds: [services.massage._id],
      room: "302",
      capacity: 1,
      slotIntervalMinutes: 40,
      defaultDurationMinutes: 30,
      defaultBufferMinutes: 10,
    }),
    irradiationDevice: await upsertResource({
      name: "Шарлагын аппарат 1",
      type: "device",
      category: "irradiation",
      serviceIds: [services.irradiation._id],
      room: "303",
      capacity: 1,
      slotIntervalMinutes: 30,
      defaultDurationMinutes: 20,
      defaultBufferMinutes: 10,
    }),
  };

  const patients = {
    p1: await upsertPatient({
      registrationNumber: "NUM-DEMO-0001",
      firstname: users.patient1.firstname,
      lastname: users.patient1.lastname,
      phone: users.patient1.phone,
      email: users.patient1.email,
      gender: "male",
      birthdate: users.patient1.birthdate,
      category: "student",
      bloodType: "A+",
      allergies: ["Пенициллин"],
      chronicConditions: ["Харшлын ринит"],
      regularMedications: ["Cetirizine"],
      medicalWarnings: ["Пенициллинд харшилтай"],
      address: "БЗД, 14-р хороо",
      notes: "Patient portal smoke test account.",
      universityId: "NUM20D1234",
      emergencyContact: { name: "Энхтуяа", phone: "99119911", relationship: "Ээж" },
      registeredBy: users.operator._id,
      userId: users.patient1._id,
    }),
    p2: await upsertPatient({
      registrationNumber: "NUM-DEMO-0002",
      firstname: users.patient2.firstname,
      lastname: users.patient2.lastname,
      phone: users.patient2.phone,
      email: users.patient2.email,
      gender: "female",
      birthdate: users.patient2.birthdate,
      category: "employee",
      bloodType: "O+",
      chronicConditions: ["Нойргүйдэл"],
      address: "СБД, 6-р хороо",
      notes: "Stress-related active visit demo.",
      emergencyContact: { name: "Батболд", phone: "99118822", relationship: "Нөхөр" },
      registeredBy: users.operator._id,
      userId: users.patient2._id,
    }),
    p3: await upsertPatient({
      registrationNumber: "NUM-DEMO-0003",
      firstname: users.patient3.firstname,
      lastname: users.patient3.lastname,
      phone: users.patient3.phone,
      email: users.patient3.email,
      gender: "female",
      birthdate: users.patient3.birthdate,
      category: "student",
      bloodType: "B+",
      notes: "Upcoming mental-health follow-up.",
      registeredBy: users.superadmin._id,
      userId: users.patient3._id,
    }),
    p4: await upsertPatient({
      registrationNumber: "NUM-DEMO-0004",
      firstname: users.patient4.firstname,
      lastname: users.patient4.lastname,
      phone: users.patient4.phone,
      email: users.patient4.email,
      gender: "male",
      birthdate: users.patient4.birthdate,
      category: "teacher",
      bloodType: "AB+",
      chronicConditions: ["Артерийн даралт ихсэлт"],
      notes: "Cancelled appointment demo.",
      registeredBy: users.operator._id,
      userId: users.patient4._id,
    }),
    p5: await upsertPatient({
      registrationNumber: "NUM-DEMO-0005",
      firstname: users.patient5.firstname,
      lastname: users.patient5.lastname,
      phone: users.patient5.phone,
      email: users.patient5.email,
      gender: "female",
      birthdate: users.patient5.birthdate,
      category: "student",
      bloodType: "A-",
      notes: "Irradiation device no-show demo.",
      registeredBy: users.operator._id,
      userId: users.patient5._id,
    }),
    p6: await upsertPatient({
      registrationNumber: "NUM-DEMO-0006",
      firstname: users.patient6.firstname,
      lastname: users.patient6.lastname,
      phone: users.patient6.phone,
      email: users.patient6.email,
      gender: "male",
      birthdate: users.patient6.birthdate,
      category: "employee",
      bloodType: "O-",
      chronicConditions: ["Нурууны өвдөлт"],
      regularMedications: ["Ibuprofen PRN"],
      notes: "In-progress visit demo.",
      registeredBy: users.superadmin._id,
      userId: users.patient6._id,
    }),
  };

  const time = {
    twoDaysAgo0900: plusDays(now, -2, 9, 0),
    today1000: withTime(now, 10, 0),
    tomorrow1100: plusDays(now, 1, 11, 0),
    yesterday1400: plusDays(now, -1, 14, 0),
    today1530: withTime(now, 15, 30),
    today1620: withTime(now, 16, 20),
    today1300: withTime(now, 13, 0),
  };

  const appointments = {
    completed: await upsertAppointment({
      patientId: patients.p1._id,
      doctorId: staff.doctorGeneral._id,
      serviceId: services.consult._id,
      resourceId: resources.doctorGeneral._id,
      scheduledDate: time.twoDaysAgo0900,
      scheduledTime: "09:00",
      scheduledStart: time.twoDaysAgo0900,
      scheduledEnd: withTime(time.twoDaysAgo0900, 9, 20),
      blockedUntil: withTime(time.twoDaysAgo0900, 9, 25),
      durationMinutes: 20,
      bufferMinutes: 5,
      appointmentKind: "consultation",
      type: "follow_up",
      status: "completed",
      queueNumber: 3,
      chiefComplaint: "Толгой өвдөх, ядаргаа",
      notes: "Demo completed consultation",
      createdBy: users.operator._id,
      checkedInBy: users.operator._id,
      checkedInAt: withTime(time.twoDaysAgo0900, 8, 47),
    }),
    activePatientPortal: await upsertAppointment({
      patientId: patients.p2._id,
      doctorId: staff.doctorGeneral._id,
      serviceId: services.consult._id,
      resourceId: resources.doctorGeneral._id,
      scheduledDate: time.today1000,
      scheduledTime: "10:00",
      scheduledStart: time.today1000,
      scheduledEnd: withTime(now, 10, 20),
      blockedUntil: withTime(now, 10, 25),
      durationMinutes: 20,
      bufferMinutes: 5,
      appointmentKind: "consultation",
      type: "scheduled",
      status: "completed",
      queueNumber: 6,
      chiefComplaint: "Нойргүйдэл, стресс",
      notes: "Demo appointment with linked completed visit",
      createdBy: users.operator._id,
      checkedInBy: users.operator._id,
      checkedInAt: withTime(now, 9, 42),
    }),
    upcoming: await upsertAppointment({
      patientId: patients.p3._id,
      doctorId: staff.doctorGeneral._id,
      serviceId: services.consult._id,
      resourceId: resources.doctorGeneral._id,
      scheduledDate: time.tomorrow1100,
      scheduledTime: "11:00",
      scheduledStart: time.tomorrow1100,
      scheduledEnd: plusDays(now, 1, 11, 20),
      blockedUntil: plusDays(now, 1, 11, 25),
      durationMinutes: 20,
      bufferMinutes: 5,
      appointmentKind: "consultation",
      type: "scheduled",
      status: "scheduled",
      queueNumber: 2,
      chiefComplaint: "Шалгалтын үеийн түгшүүр",
      notes: "Upcoming consultation",
      createdBy: users.superadmin._id,
    }),
    cancelled: await upsertAppointment({
      patientId: patients.p4._id,
      doctorId: staff.doctorGeneral._id,
      serviceId: services.consult._id,
      resourceId: resources.doctorGeneral._id,
      scheduledDate: time.yesterday1400,
      scheduledTime: "14:00",
      scheduledStart: time.yesterday1400,
      scheduledEnd: plusDays(now, -1, 14, 20),
      blockedUntil: plusDays(now, -1, 14, 25),
      durationMinutes: 20,
      bufferMinutes: 5,
      appointmentKind: "consultation",
      type: "scheduled",
      status: "cancelled",
      chiefComplaint: "Даралт ихсэх",
      notes: "Cancelled consultation demo",
      createdBy: users.operator._id,
      cancelledBy: users.operator._id,
      cancelledAt: plusDays(now, -1, 11, 25),
      cancelReason: "Өвчтөн өөрийн хүсэлтээр цуцалсан",
    }),
    noShowIrradiation: await upsertAppointment({
      patientId: patients.p5._id,
      serviceId: services.irradiation._id,
      resourceId: resources.irradiationDevice._id,
      scheduledDate: time.today1530,
      scheduledTime: "15:30",
      scheduledStart: time.today1530,
      scheduledEnd: withTime(now, 15, 50),
      blockedUntil: withTime(now, 16, 10),
      durationMinutes: 20,
      bufferMinutes: 10,
      appointmentKind: "device",
      type: "scheduled",
      status: "no_show",
      queueNumber: 11,
      chiefComplaint: "Шарлага эмчилгээ авах",
      notes: "No-show irradiation device demo",
      createdBy: users.operator._id,
    }),
    inProgress: await upsertAppointment({
      patientId: patients.p6._id,
      doctorId: staff.doctorGeneral._id,
      serviceId: services.consult._id,
      resourceId: resources.doctorGeneral._id,
      scheduledDate: time.today1620,
      scheduledTime: "16:20",
      scheduledStart: time.today1620,
      scheduledEnd: withTime(now, 16, 40),
      blockedUntil: withTime(now, 16, 45),
      durationMinutes: 20,
      bufferMinutes: 5,
      appointmentKind: "consultation",
      type: "walk_in",
      status: "in_progress",
      queueNumber: 12,
      chiefComplaint: "Нуруу чилж өвдөх",
      notes: "In-progress doctor queue demo",
      createdBy: users.operator._id,
      checkedInBy: users.operator._id,
      checkedInAt: withTime(now, 16, 2),
    }),
    infusionScheduled: await upsertAppointment({
      patientId: patients.p1._id,
      nurseId: staff.nurse._id,
      assignedStaffId: staff.nurse._id,
      serviceId: services.infusion._id,
      resourceId: resources.infusionRoom._id,
      scheduledDate: time.today1300,
      scheduledTime: "13:00",
      scheduledStart: time.today1300,
      scheduledEnd: withTime(now, 14, 30),
      blockedUntil: withTime(now, 14, 30),
      durationMinutes: 90,
      bufferMinutes: 0,
      appointmentKind: "infusion",
      type: "scheduled",
      status: "scheduled",
      queueNumber: 7,
      chiefComplaint: "Шингэн сэлбэх",
      notes: "Capacity-room scheduling demo",
      createdBy: users.operator._id,
    }),
  };

  const visits = {
    completed: await upsertVisit({
      appointmentId: appointments.completed._id,
      patientId: patients.p1._id,
      doctorId: staff.doctorGeneral._id,
      visitDate: withTime(time.twoDaysAgo0900, 9, 18),
      visitType: "scheduled",
      status: "completed",
      chiefComplaint: "Толгой өвдөх, ядаргаа",
      historyOfPresentIllness: "Сүүлийн 5 хоног хичээлийн ачаалал нэмэгдэж, ус бага ууснаас толгой өвдсөн.",
      physicalExamination: "Ерөнхий байдал тогтвортой, халуураагүй, мэдрэлийн гаж өөрчлөлтгүй.",
      assessment: "Stress-related tension headache",
      plan: "Амралт, шингэн сайн уух, шаардлагатай үед өвдөлт намдаах эм хэрэглэх.",
      notes: "3 хоногийн дараа дахин хянах зөвлөмж өгсөн.",
      createdBy: users.doctorGeneral._id,
      completedAt: withTime(time.twoDaysAgo0900, 9, 41),
    }),
    patientVisible: await upsertVisit({
      appointmentId: appointments.activePatientPortal._id,
      patientId: patients.p2._id,
      doctorId: staff.doctorGeneral._id,
      visitDate: withTime(now, 10, 18),
      visitType: "scheduled",
      status: "completed",
      chiefComplaint: "Нойргүйдэл, стресс",
      historyOfPresentIllness: "Сүүлийн хоёр долоо хоног ажлын ачаалал ихэсч, нойр алдагдсан.",
      physicalExamination: "Ерөнхий байдал тогтвортой, pulse бага зэрэг түргэссэн.",
      assessment: "Acute stress response",
      plan: "Ажлын ачаалал тохируулах, sleep hygiene зөвлөмж, 7 хоногийн дараа follow-up.",
      notes: "Patient portal дээр харагдах жишиг completed visit.",
      createdBy: users.doctorGeneral._id,
      completedAt: withTime(now, 10, 46),
    }),
    inProgress: await upsertVisit({
      appointmentId: appointments.inProgress._id,
      patientId: patients.p6._id,
      doctorId: staff.doctorGeneral._id,
      visitDate: withTime(now, 16, 28),
      visitType: "scheduled",
      status: "active",
      chiefComplaint: "Нуруу чилж өвдөх",
      historyOfPresentIllness: "Сүүлийн сар удаан сууж ажилласнаас бүсэлхий орчим зовиуртай болсон.",
      physicalExamination: "Булчингийн чангаралттай, мэдрэлийн алдагдалгүй.",
      assessment: "Mechanical low back pain",
      plan: "Сунгалтын дасгал, ачаалал бууруулах, шаардлагатай үед NSAID хэрэглэх.",
      notes: "2 долоо хоногийн дараа эргэн үзнэ.",
      createdBy: users.doctorGeneral._id,
    }),
  };

  await upsertVital({
    visitId: visits.completed._id,
    patientId: patients.p1._id,
    recordedBy: users.nurse._id,
    temperature: 36.7,
    bloodPressureSystolic: 118,
    bloodPressureDiastolic: 76,
    heartRate: 74,
    respiratoryRate: 16,
    oxygenSaturation: 98,
    weight: 68,
    height: 176,
  });

  await upsertVital({
    visitId: visits.patientVisible._id,
    patientId: patients.p2._id,
    recordedBy: users.nurse._id,
    temperature: 36.5,
    bloodPressureSystolic: 110,
    bloodPressureDiastolic: 72,
    heartRate: 82,
    respiratoryRate: 17,
    oxygenSaturation: 99,
    weight: 57,
    height: 164,
  });

  await upsertVital({
    visitId: visits.inProgress._id,
    patientId: patients.p6._id,
    recordedBy: users.nurse._id,
    temperature: 36.4,
    bloodPressureSystolic: 124,
    bloodPressureDiastolic: 81,
    heartRate: 79,
    respiratoryRate: 16,
    oxygenSaturation: 98,
    weight: 83,
    height: 179,
  });

  await upsertDiagnosis({
    visitId: visits.completed._id,
    patientId: patients.p1._id,
    doctorId: staff.doctorGeneral._id,
    icdCode: "MG30.1",
    icdTitle: "Headache attributable to stress",
    icdLinearizationUri: "http://id.who.int/icd/release/11/2026-01/mms/557175275",
    icdFoundationUri: "http://id.who.int/icd/entity/557175275",
    icdParentUri: "http://id.who.int/icd/release/11/2026-01/mms/702530275",
    name: "Stress-related tension headache",
    description: "Хэт ачаалал, ус бага ууснаас сэдэрсэн толгой өвдөлт.",
    type: "primary",
    severity: "mild",
    notes: "Амралт, шингэн сайжруулах зөвлөмж өгсөн.",
    createdBy: users.doctorGeneral._id,
  });

  await upsertDiagnosis({
    visitId: visits.patientVisible._id,
    patientId: patients.p2._id,
    doctorId: staff.doctorGeneral._id,
    icdCode: "6B43",
    icdTitle: "Adjustment disorder",
    icdLinearizationUri: "http://id.who.int/icd/release/11/2026-01/mms/264310751",
    icdFoundationUri: "http://id.who.int/icd/entity/264310751",
    icdParentUri: "http://id.who.int/icd/release/11/2026-01/mms/2083459613",
    name: "Acute stress response",
    description: "Ажлын ачааллаас шалтгаалсан нойргүйдэл, түгшүүр.",
    type: "primary",
    severity: "moderate",
    notes: "Follow-up төлөвлөсөн.",
    createdBy: users.doctorGeneral._id,
  });

  await upsertDiagnosis({
    visitId: visits.inProgress._id,
    patientId: patients.p6._id,
    doctorId: staff.doctorGeneral._id,
    icdCode: "ME84.2",
    icdTitle: "Low back pain",
    icdLinearizationUri: "http://id.who.int/icd/release/11/2026-01/mms/2058176366",
    icdFoundationUri: "http://id.who.int/icd/entity/2058176366",
    icdParentUri: "http://id.who.int/icd/release/11/2026-01/mms/1036687330",
    name: "Mechanical low back pain",
    description: "Удаан суух ажилтай холбоотой нурууны өвдөлт.",
    type: "primary",
    severity: "moderate",
    notes: "Дасгал болон posture зөвлөмж өгсөн.",
    createdBy: users.doctorGeneral._id,
  });

  await upsertPrescription({
    prescriptionNumber: "RX-DEMO-001",
    visitId: visits.completed._id,
    patientId: patients.p1._id,
    doctorId: staff.doctorGeneral._id,
    status: "dispensed",
    notes: "Completed visit medication pack",
    createdBy: users.doctorGeneral._id,
    items: [
      {
        medicationName: "Paracetamol",
        dosage: "500mg",
        frequency: "Өдөрт 3 удаа",
        duration: "3 өдөр",
        quantity: 9,
        unit: "tablet",
        instructions: "Хоолны дараа ууна.",
      },
    ],
  });

  await upsertPrescription({
    prescriptionNumber: "RX-DEMO-002",
    visitId: visits.patientVisible._id,
    patientId: patients.p2._id,
    doctorId: staff.doctorGeneral._id,
    status: "active",
    notes: "Sleep hygiene support",
    createdBy: users.doctorGeneral._id,
    items: [
      {
        medicationName: "Melatonin",
        dosage: "3mg",
        frequency: "Унтахын өмнө",
        duration: "7 өдөр",
        quantity: 7,
        unit: "tablet",
        instructions: "7 хоног хэрэглээд дахин үнэлнэ.",
      },
    ],
  });

  await upsertPrescription({
    prescriptionNumber: "RX-DEMO-003",
    visitId: visits.inProgress._id,
    patientId: patients.p6._id,
    doctorId: staff.doctorGeneral._id,
    status: "active",
    notes: "Back-pain management",
    createdBy: users.doctorGeneral._id,
    items: [
      {
        medicationName: "Ibuprofen",
        dosage: "400mg",
        frequency: "Өдөрт 2 удаа",
        duration: "5 өдөр",
        quantity: 10,
        unit: "tablet",
        instructions: "Хоолны дараа ууна.",
      },
      {
        medicationName: "Topical Diclofenac Gel",
        dosage: "2%",
        frequency: "Өдөрт 2 удаа",
        duration: "7 өдөр",
        quantity: 1,
        unit: "tube",
        instructions: "Өвдөж буй хэсэгт нимгэн түрхэнэ.",
      },
    ],
  });

  await upsertUnavailableBlock({
    serviceId: services.massage._id,
    resourceId: resources.massageChair._id,
    startAt: withTime(now, 12, 0),
    endAt: withTime(now, 13, 0),
    reason: "Төхөөрөмжийн ариутгал",
    note: "Lunch cleaning block for schedule management page",
    createdBy: users.superadmin._id,
  });

  await replaceNotifications("seed-demo-2026", [
    {
      userId: users.superadmin._id,
      title: "[Demo] Өдрийн ачааллын тойм",
      type: "info",
      body: {
        scheduled: 2,
        completed: 2,
        inProgress: 1,
        cancelled: 1,
        noShow: 1,
      },
    },
    {
      userId: users.doctorGeneral._id,
      title: "[Demo] Шинэ үзлэг хүлээж байна",
      type: "appointment",
      body: {
        patient: `${patients.p6.lastname} ${patients.p6.firstname}`,
        appointmentId: appointments.inProgress._id,
        scheduledTime: "16:20",
      },
    },
    {
      userId: users.patient2._id,
      title: "[Demo] Үзлэгийн тэмдэглэл бэлэн боллоо",
      type: "success",
      body: {
        visitId: visits.patientVisible._id,
        prescriptionNumber: "RX-DEMO-002",
      },
    },
    {
      userId: users.patient4._id,
      title: "[Demo] Цаг цуцлагдсан",
      type: "warning",
      body: {
        appointmentId: appointments.cancelled._id,
        reason: "Өвчтөн өөрийн хүсэлтээр цуцалсан",
      },
    },
  ]);

  await replaceAuditLogs("seed-demo-2026", [
    {
      userId: users.operator._id,
      action: "create",
      resource: "appointment",
      resourceId: appointments.activePatientPortal._id.toString(),
      details: { patient: patients.p2.registrationNumber, flow: "patient-visible-visit" },
    },
    {
      userId: users.doctorGeneral._id,
      action: "update",
      resource: "visit",
      resourceId: visits.patientVisible._id.toString(),
      details: { status: "completed", patient: patients.p2.registrationNumber },
    },
    {
      userId: users.doctorGeneral._id,
      action: "create",
      resource: "prescription",
      resourceId: "RX-DEMO-002",
      details: { patient: patients.p2.registrationNumber },
    },
    {
      userId: users.superadmin._id,
      action: "create",
      resource: "unavailable_block",
      resourceId: resources.massageChair._id.toString(),
      details: { reason: "Төхөөрөмжийн ариутгал" },
    },
  ]);

  const summary = await countSummary();
  console.log("Demo seed completed");
  console.log(summary);
  console.log("Demo logins:");
  console.log("  superadmin  99335671 / Test!123");
  console.log("  doctor      99110011 / Doctor!123");
  console.log("  nurse       99110012 / Nurse!123");
  console.log("  operator    99110013 / Operator!123");
  console.log("  patient     88112233 / Patient!123");

  await disconnectDb();
}

seedDemo().catch(async (error) => {
  console.error("Demo seed failed:", error);
  await disconnectDb();
  process.exit(1);
});
